use_frameworks!
platform :ios, '10.0'

target 'SnapshotTesting-Nimble_Example' do

  target 'SnapshotTesting-Nimble_ExampleTests' do
    inherit! :search_paths

    pod 'SnapshotTesting', '1.0.0'
    pod 'SnapshotTesting-Nimble', :path => '../'
    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
  end
end
