use_frameworks!

target 'SnapshotTesting-Nimble_Example' do
  pod 'SnapshotTesting-Nimble', :path => '../'

  target 'SnapshotTesting-Nimble_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
