version: 2
jobs:
  build:

    # Specify the Xcode version to use
    macos:
      xcode: "10.1.0"

    steps:
      - checkout

      - run:
          name: "Create output dir"
          command: mkdir output      

      - run:
          name: Install CocoaPods
          command: pod install

      - run:
          name: "Run tests in Swift"
          command: xcodebuild -workspace 'Example/SnapshotTesting-Nimble.xcworkspace' -sdk 'iphonesimulator' -scheme 'SnapshotTesting-Nimble-Example' -destination 'name=iPhone 8' SWIFT_VERSION=4.2 build test | tee output/xcodebuild_swift.log | xcpretty --color --simple
          environment:
            SNAPSHOT_ARTIFACTS: /tmp/__SnapshotArtifacts__

      - store_artifacts:
          path: output/
      - store_artifacts:
          path: /tmp/__SnapshotArtifacts__

