name: Test

on:
  push:
 
jobs:

  test-job:
    name: Test
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing via SPM
        run: |
          ./ci-scripts/test.sh
