name: Test, Build, and Release

on:
  push:
    branches: [ kemal/spm-1 ]
    # Change this to be done on release/x.y.z instead or TAG x.y.z?
 
jobs:

  test-job:
    name: Test
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testing via SPM
        run: |
          ./ci-scripts/test.sh

  package-job:
    name: Build
    runs-on: macos-latest
    needs: test-job
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
      BUILD_NUMBER: ${{ github.run_number }}
      BUILD_NAME: ${{ github.ref }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
 
      - name: Building via SPM
        run: |
          ./ci-scripts/build.sh
