name: Test

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test-job:
    name: Test
    runs-on: macos-11
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 13.0

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Tests
        run: |
          ./ci-scripts/test.sh